### ISSUE TITLE
com.intellij.openapi.components.State missing element storages [df28009ad8]

### ISSUE THREAD

**Issue by aem-intellij-plugin-error-reporter** [aem-intellij-plugin-error-reporter/auto-generated-issues-storage#25] opened 2018-10-16 19:26 UTC
## Description
*No description*
## Exception
```
java.lang.annotation.IncompleteAnnotationException: com.intellij.openapi.components.State missing element storages
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:80)
	at com.sun.proxy.$Proxy18.storages(Unknown Source)
	at com.intellij.configurationStore.ComponentStoreImpl.getStorageSpecs(ComponentStoreImpl.kt:322)
	at com.intellij.configurationStore.ProjectStoreImpl.getStorageSpecs(ProjectStoreImpl.kt:248)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistentComponent(ComponentStoreImpl.kt:262)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at co.nums.intellij.aem.service.JcrRootsKt.getJcrRoots(JcrRoots.kt:74)
	at co.nums.intellij.aem.icons.providers.JcrRootIconProvider.getIcon(JcrRootIconProvider.kt:15)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.setupIcon(PsiDirectoryNode.java:152)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.updateImpl(PsiDirectoryNode.java:122)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$1.run(AbstractPsiBasedNode.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:938)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:132)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:892)
	at com.intellij.ide.util.treeView.AbstractTreeUi.collectNodesToInsert(AbstractTreeUi.java:2256)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4500(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1399)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:275)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.openapi.util.ActionCallback.notify(ActionCallback.java:156)
	at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2091)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$38$1.perform(AbstractTreeUi.java:1983)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2186)
	at com.intellij.ide.util.treeView.AbstractTreeUi$38.perform(AbstractTreeUi.java:1978)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
## Error context
```
Last Action:       
Plugin Version:    0.8.5
OS Name:           Windows 8
Java Version:      1.8.0_51
Java VM Vendor:    Oracle Corporation
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-143.1184
App Version:       15.0.2
```

**Comment by aem-intellij-plugin-error-reporter** [comment] 2018-10-31 14:48
## Description
*No description*
## Error context
```
Last Action:       Vcs.Push
Plugin Version:    0.8.5
OS Name:           Mac OS X
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-182.4892.20
App Version:       2018.2.5
```

**Comment by aem-intellij-plugin-error-reporter** [comment] 2018-11-13 22:31
## Description
*No description*
## Error context
```
Last Action:       FindUsages
Plugin Version:    0.8.6
OS Name:           Mac OS X
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-173.3727.127
App Version:       2017.3
```

**Comment by aem-intellij-plugin-error-reporter** [comment] 2019-01-02 13:45
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9
OS Name:           Windows 10
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-183.4886.37
App Version:       2018.3.2
```

**Comment by karollewandowski** [comment] 2019-01-02 23:17
This issue is pretty strange. An error says that `@State` annotation on `JcrRoots` component does not specify required `storages` parameter. This parameter is specified in `@com.intellij.openapi.components.State` as `Storage[] storages() default {};` (has default value, so is not required) since 2016 and errors are reported from versions released in 2017/2018.
I couldn't reproduce this issue and as a possible fix, I decided to change `@State` annotation for `JcrRoots` to `@State(name = "JcrRoots", storages = [])` and hope this will work.

Please update the plugin to 0.9.1.

**Closed as completed by karollewandowski** 2019-01-02 23:17 UTC
Labels: auto-generated
